name: Streams – Ensure Indexes
on:
  schedule:
    - cron: "5 3 1 * *" # monthly at 03:05 UTC
  workflow_dispatch:
jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://waternews.onrender.com
      WATERNEWS_CRON_SECRET: ${{ secrets.WATERNEWS_CRON_SECRET }}
    steps:
      - name: Ensure DB indexes
        if: ${{ env.WATERNEWS_CRON_SECRET != '' }}
        run: |
          curl -fsS -X POST -H "Authorization: Bearer $WATERNEWS_CRON_SECRET" \
            "$BASE_URL/api/admin/cron/ensure-indexes"

