name: Streams – Trending Refresh
on:
  schedule:
    - cron: "3,18,33,48 * * * *" # every ~15 min, offset from :00 (UTC)
  workflow_dispatch:
jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://waternews.onrender.com
      WATERNEWS_CRON_SECRET: ${{ secrets.WATERNEWS_CRON_SECRET }}
    steps:
      - name: Refresh trending cache
        if: ${{ env.WATERNEWS_CRON_SECRET != '' }}
        run: |
          curl -fsS -H "Authorization: Bearer $WATERNEWS_CRON_SECRET" \
            "$BASE_URL/api/admin/cron/trending-refresh?hours=48&n=100"

